### ISSUE TITLE
[suggestion] Fork()

### ISSUE THREAD

**Issue by PabloCariel** [XiaoxiaoPu/muon#1]
Hello Friend. Because you do not use mfork () from the library libmill ?.

Sorry for my bad english.

**Comment by XiaoxiaoPu** [comment]
The master process does not call any libmill's function, so it doesn't matter.

**Comment by PabloCariel** [comment]
I can use mfork() and there is no problem?

**Comment by XiaoxiaoPu** [comment]
@PabloCariel It's OK to use mfork().

**Comment by PabloCariel** [comment]
a doubt that I have, minilzo is better than snappy?

**Comment by XiaoxiaoPu** [comment]
@PabloCariel minilzo is quiet easy to use, and can be embedded in source files.
