### ISSUE TITLE
Can I cross compile a version for MIPS64

### ISSUE THREAD

**Issue by cutemanworking** [XiaoxiaoPu/muon#2]
Can I change the setting in "--host=arm-unknown-linux-gnueabihf" for my Linux which running with MIPS64 cpu ?

**Comment by XiaoxiaoPu** [comment]
@cutemanworking 
Yes. However, only unit tests are tested under qemu-mips, not fully tested. A sample build log is attached as `log.txt`.
[log.txt](https://github.com/XiaoxiaoPu/muon/files/456997/log.txt)
