### ISSUE TITLE
error when run "autoreconf -if" 

### ISSUE THREAD

**Issue by cutemanworking** [XiaoxiaoPu/muon#3]
I can install this software in ubuntu 14 but following error when run "autoreconf -if" in Debian 7. any package I need to install?

src/Makefile.am:5: compiling `3rd/minilzo.c' in subdir requires `AM_PROG_CC_C_O' in `configure.ac'
src/Makefile.am: installing `./depcomp'
autoreconf: automake failed with exit status: 1

**Comment by XiaoxiaoPu** [comment]
http://lmgtfy.com/?q=automake+AM_PROG_CC_C_O#
