### ISSUE TITLE
routing in client

### ISSUE THREAD

**Issue by cutemanworking** [XiaoxiaoPu/muon#4]
what will the program do if  set "route=yes" in client.conf?

I tested and guess it will try to add default to the tun "vpn0". Since my client system already has a default gateway which point to the my internal router ip.  As result,  program showed error. when I set "route=no", program can run well. The question turned to be -- how can I route traffic via the tun "vpn0"? 

like "shadowvpn", run a shell script once the "vpn0" up maybe an idea,  but any simpler way there? :-)

**Comment by XiaoxiaoPu** [comment]
https://github.com/XiaoxiaoPu/muon/blob/master/src/utils.c#L163

It adds routes to direct traffic to vpn device.
