### ISSUE TITLE
undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by cutemanworking** [XiaoxiaoPu/muon#5]
sorry to bother you again. 
still try to compile in my debian 7 box,  got following error when "make" in muon folder:
libmill/timer.c:52: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
Makefile:278: recipe for target 'muon' failed
make[2]: *** [muon] Error 1

how can i fix it?

**Comment by XiaoxiaoPu** [comment]
http://lmgtfy.com/?q=undefined+reference+to+%60clock_gettime%27
